# --- ETAPA 1: Compilación ---
# Usamos una imagen que tiene Java y Maven instalados para construir el proyecto
FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /ecommerce-api
  
  # Copiamos el archivo de configuración de Maven y el código fuente
COPY pom.xml .
COPY src ./src
  
  # Compilamos el proyecto saltándonos los tests para ir más rápido
RUN mvn clean package -DskipTests
  
  # --- ETAPA 2: Imagen Final ---
  # Usamos una imagen limpia y pequeña que solo tiene el entorno de ejecución (JRE)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
  
  # Copiamos el archivo .jar generado en la ETAPA 1 (fíjate en el --from=build)
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]