# --- STEP 1: Compilation ---
FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /ecommerce-api
  
  # Copy the master parent configuration
COPY pom.xml .

 # Copy submodules and sub-apps explicitly
COPY apps ./apps/
COPY modules ./modules/
  
  # Compile the whole multi-module project
RUN mvn clean package -DskipTests
  
  # --- STEP 2: Final Runtime Image ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /ecommerce-api
  
  # Copy the finished fat JAR file from the monolith-app build target directory
COPY --from=build /ecommerce-api/apps/monolith-app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]